
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8502
  Network URL: http://156.67.221.86:8502
  External URL: http://156.67.221.86:8502


Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8503
  Network URL: http://156.67.221.86:8503
  External URL: http://156.67.221.86:8503

/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV3/utils.py:8: LangChainDeprecationWarning: Please see the migration guide at: https://python.langchain.com/docs/versions/migrating_memory/
  return ConversationBufferMemory(
/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV3/utils.py:8: LangChainDeprecationWarning: Please see the migration guide at: https://python.langchain.com/docs/versions/migrating_memory/
  return ConversationBufferMemory(
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8502
  Network URL: http://156.67.221.86:8502
  External URL: http://156.67.221.86:8502


Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8503
  Network URL: http://156.67.221.86:8503
  External URL: http://156.67.221.86:8503

/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/utils.py:8: LangChainDeprecationWarning: Please see the migration guide at: https://python.langchain.com/docs/versions/migrating_memory/
  return ConversationBufferMemory(
/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/utils.py:8: LangChainDeprecationWarning: Please see the migration guide at: https://python.langchain.com/docs/versions/migrating_memory/
  return ConversationBufferMemory(
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3
Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].
2025-05-08 20:02:37.181 Uncaught app execution
Traceback (most recent call last):
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 593, in code_to_exec
    exec(code, module.__dict__)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/app_user.py", line 84, in <module>
    controlador.generar_respuesta(input, model_choice, MEMORY)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/controlador.py", line 22, in generar_respuesta
    self.logica_chat.generar_respuesta(entrada_usuario, modelo_elegido, memoria)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/logica_chat.py", line 96, in generar_respuesta
    respuesta = self.modelo_chat.invoke(prompt_final)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 307, in invoke
    self.generate_prompt(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 843, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 683, in generate
    self._generate_with_cache(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 908, in _generate_with_cache
    result = self._generate(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 964, in _generate
    response: GenerateContentResponse = _chat_with_retry(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 204, in _chat_with_retry
    return _chat_with_retry(**kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 202, in _chat_with_retry
    raise e
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 186, in _chat_with_retry
    return generation_method(**kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 867, in generate_content
    response = rpc(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
]
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3
Add of existing embedding ID: Temario2021.pdf_1
Add of existing embedding ID: Temario2021.pdf_2
Add of existing embedding ID: Temario2021.pdf_3
Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].
2025-05-08 20:09:52.892 Uncaught app execution
Traceback (most recent call last):
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 593, in code_to_exec
    exec(code, module.__dict__)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/app_admin.py", line 35, in <module>
    pg.run()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/streamlit/navigation/page.py", line 306, in run
    exec(code, module.__dict__)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/pruebas_archivos.py", line 101, in <module>
    controlador.generar_respuesta(input, model_choice, TEST_MEMORY)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/controlador.py", line 22, in generar_respuesta
    self.logica_chat.generar_respuesta(entrada_usuario, modelo_elegido, memoria)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/logica_chat.py", line 96, in generar_respuesta
    respuesta = self.modelo_chat.invoke(prompt_final)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 307, in invoke
    self.generate_prompt(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 843, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 683, in generate
    self._generate_with_cache(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 908, in _generate_with_cache
    result = self._generate(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 964, in _generate
    response: GenerateContentResponse = _chat_with_retry(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 204, in _chat_with_retry
    return _chat_with_retry(**kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 202, in _chat_with_retry
    raise e
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 186, in _chat_with_retry
    return generation_method(**kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 867, in generate_content
    response = rpc(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
]
Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].
2025-05-08 20:32:35.586 Uncaught app execution
Traceback (most recent call last):
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 593, in code_to_exec
    exec(code, module.__dict__)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/app_user.py", line 84, in <module>
    controlador.generar_respuesta(input, model_choice, MEMORY)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/controlador.py", line 22, in generar_respuesta
    self.logica_chat.generar_respuesta(entrada_usuario, modelo_elegido, memoria)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/logica_chat.py", line 96, in generar_respuesta
    respuesta = self.modelo_chat.invoke(prompt_final)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 307, in invoke
    self.generate_prompt(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 843, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 683, in generate
    self._generate_with_cache(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 908, in _generate_with_cache
    result = self._generate(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 964, in _generate
    response: GenerateContentResponse = _chat_with_retry(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 204, in _chat_with_retry
    return _chat_with_retry(**kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 202, in _chat_with_retry
    raise e
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 186, in _chat_with_retry
    return generation_method(**kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 867, in generate_content
    response = rpc(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
]
Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].
2025-05-08 20:33:41.946 Uncaught app execution
Traceback (most recent call last):
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 593, in code_to_exec
    exec(code, module.__dict__)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/app_user.py", line 84, in <module>
    controlador.generar_respuesta(input, model_choice, MEMORY)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/controlador.py", line 22, in generar_respuesta
    self.logica_chat.generar_respuesta(entrada_usuario, modelo_elegido, memoria)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/ChatbotV4/logica_chat.py", line 96, in generar_respuesta
    respuesta = self.modelo_chat.invoke(prompt_final)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 307, in invoke
    self.generate_prompt(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 843, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 683, in generate
    self._generate_with_cache(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 908, in _generate_with_cache
    result = self._generate(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 964, in _generate
    response: GenerateContentResponse = _chat_with_retry(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 204, in _chat_with_retry
    return _chat_with_retry(**kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 202, in _chat_with_retry
    raise e
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/langchain_google_genai/chat_models.py", line 186, in _chat_with_retry
    return generation_method(**kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 867, in generate_content
    response = rpc(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/arduinoenparques/homes/mgltchm/Luis/venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
]
